language: swift

osx_image: xcode11

xcode_project: Demo/SMCircleColorPicker.xcodeproj
xcode_scheme: SMCircleColorPicker
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone X

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project Demo/SMCircleColorPicker.xcodeproj -scheme SMCircleColorPicker -destination platform\=iOS\ Simulator,OS\=13.0,name\=iPhone\ 8 build test | xcpretty
